version: '3.8'

services:
    database:
        container_name: campfarfelu-database
        image: postgres:13.2-alpine
        environment:
          - POSTGRES_USER=${DATABASE_ROOT_USER}
          - POSTGRES_PASSWORD=${DATABASE_ROOT_USER}
        ports:
          - ${DATABASE_PORT}:5432
        volumes:
          - campfarfelu-database:/var/lib/postgresql/data
          - ./prisma/initialize.sql:/docker-entrypoint-initdb.d/initialize.sql:ro

    adminer:
        container_name: campfarfelu-adminer
        image: adminer:latest
        depends_on:
            - database
        ports:
            - ${ADMINER_PORT}:8080
        volumes:
            - ./adminer/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro  

volumes:
    campfarfelu-database:
