version: '3'

services:
    api:
        container_name: campfarfelu-api
        build:
            context: .
            dockerfile: Dockerfile
        image: campfarfelu/campfarfelu-api
        ports:
            - ${API_PORT:-3000}:${API_PORT:-3000}
        links:
            - database
        environment:
            API_JWT_SECRET: ${API_JWT_SECRET}
