version: '3'

services:
    mariadb:
        container_name: campfarfelu-mariadb
        restart: always
        image: mariadb:10.4
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - ${DB_PORT}:3306
        volumes:
            - campfarfelu-db:/var/lib/mysql

    phpmyadmin:
        container_name: campfarfelu-pma
        restart: always
        image: phpmyadmin/phpmyadmin
        ports:
            - ${PMA_PORT:-8000}:80
        links:
            - mariadb
        environment: 
            PMA_HOST: mariadb
            PMA_ABSOLUTE_URI: ${PMA_URL}

volumes:
    campfarfelu-db:
    campfarfelu-imgp:
